server:
  port: 8906

spring:
  cloud:
    gateway:
      default-filters:
      - RemoveRequestHeader=inServer
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
      routes:
      - id: andromedaRoute
        uri: http://andromeda:8906/
        predicates:
        - Path=/wormhole/andromeda/**
        filters:
        - RewritePath=/wormhole/andromeda/(?<RID>.*), /andromeda/$\{RID}
      - id: milkywayRoute
        uri: http://milkyway:8906/
        predicates:
        - Path=/wormhole/milkyway/**
        filters:
        - RewritePath=/wormhole/milkyway/(?<RID>.*), /milkyway/$\{RID}
      - id: triangulumRoute
        uri: http://triangulum:8906/
        predicates:
        - Path=/wormhole/triangulum/**
        filters:
        - RewritePath=/wormhole/triangulum/(?<RID>.*), /triangulum/$\{RID}
      - id: mothallahRoute
        uri: http://mothallah:80/
        predicates:
        - Path=/wormhole/mothallah/**
        filters:
        - RewritePath=/wormhole/mothallah/(?<RID>.*), /mothallah/$\{RID}
      - id: leobRoute
        uri: http://leob:8906/
        predicates:
        - Path=/wormhole/leob/**
        filters:
        - RewritePath=/wormhole/leob/(?<RID>.*), /leob/$\{RID}
      - id: carinaRoute
        uri: http://carina:8906/
        predicates:
        - Path=/wormhole/carina/**
        filters:
        - RewritePath=/wormhole/carina/(?<RID>.*), /carina/$\{RID}
      - id: carinaWsRoute
        uri: ws://carina:8906/
        predicates:
        - Path=/wormhole/carina/**
        filters:
        - RewritePath=/wormhole/carina/(?<RID>.*), /carina/$\{RID}

  datasource:
    url: jdbc:postgresql://pgsql/universe?currentSchema=wormhole
    username: postgres
    password: 123456
  redis:
    host: redis
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 1
        max-wait: 1000ms

jwt:
  issuer: o
  # use sign (rsa path empty)
  sign: andromeda
  # use rsa (rsa path not empty)
  rsaPrivatePath: config/jwt-private.pem
  rsaPublicPath: config/jwt-public.pem
  expMinute: 10
  refreshExpMinute: 600
