server:
  port: 0
      
spring:
  cloud:
    gateway:
      default-filters:
      - RemoveRequestHeader=inServer
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
      routes:
      - id: andromedaRoute
        uri: http://127.0.0.1:3333/
        predicates:
        - Path=/wormhole/andromeda/**
        filters:
        - RewritePath=/wormhole/andromeda/(?<RID>.*), /andromeda/$\{RID}
  datasource:
    url: jdbc:postgresql://127.0.0.1/universe?currentSchema=wormhole
    username: postgres
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 1000
          max-idle: 10
          min-idle: 1
          max-wait: 1s

jwt:
  issuer: o
  # use sign (rsa path empty)
  sign: andromeda
  # use rsa (rsa path not empty)
  rsaPrivatePath: src/main/resources/jwt-private.pem
  rsaPublicPath: src/main/resources/jwt-public.pem
  expMinute: 10
  refreshExpMinute: 600
